[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"
name = "stc_ts_dep_graph"
publisg = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
auto_impl = "0.4.1"
derivative = "2.2.0"
derive_more = "0.99.16"
once_cell = "1.8.0"
stc_ts_utils = {path = "../utils/"}
stc_utils = {path = "../../utils/"}
swc_atoms = "0.2.7"
swc_common = "0.11.6"
swc_ecma_ast = "0.49.4"
swc_ecma_parser = "0.67.0"
swc_ecma_visit = "0.35.2"
tracing = "0.1.26"
