[package]
authors = ["강동윤 <kdy1@dudy.kr"]
edition = "2018"
name = "stc_ts_file_analyzer_macros"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
pmutil = "0.5.1"
proc-macro2 = "1"
quote = "1"
swc_common = "0.10.8"
swc_ecma_ast = "0.36.1"
swc_ecma_parser = "0.44.0"
swc_macros_common = "0.3"
syn = {version = "1", features = ["full"]}
