[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2021"
name = "stc_ts_passes"
publish = false
version = "0.1.0"

[dependencies]
ahash = "0.7.2"
fxhash = "0.2.1"
rnode = {path = "../rnode"}
stc_ts_ast_rnode = {path = "../stc_ts_ast_rnode"}
stc_ts_errors = {path = "../stc_ts_errors"}
stc_ts_types = {path = "../stc_ts_types"}
stc_ts_utils = {path = "../stc_ts_utils"}
stc_utils = {path = "../stc_utils"}
swc_atoms = "0.4.33"
swc_common = "0.29.27"
