[package]
authors = ["강동윤 <kdy1@dudy.kr>"]
edition = "2018"
name = "stc_ts_errors"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backtrace = "0.3.55"
fxhash = "0.2.1"
rnode = {path = "../../rnode"}
slog = "2.7.0"
static_assertions = "1.1.0"
stc_ts_ast_rnode = {path = "../ast_rnode"}
stc_ts_types = {path = "../types"}
swc_atoms = "0.2.5"
swc_common = "0.10.12"
swc_ecma_ast = "0.42.0"
swc_ecma_codegen = "0.50.1"
