[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"
name = "stc_ts_errors"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
backtrace = "0.3.60"
derivative = "2.2.0"
fxhash = "0.2.1"
rnode = {path = "../../rnode"}
static_assertions = "1.1.0"
stc_ts_ast_rnode = {path = "../ast_rnode"}
stc_ts_types = {path = "../types"}
stc_utils = {path = "../../utils"}
swc_atoms = "0.2.9"
swc_common = "0.14.6"
swc_ecma_ast = "0.58.0"
swc_ecma_codegen = "0.80.0"
tracing = "0.1.26"
