edition = "2021"
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Crate"
max_width = 140
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
