[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"
name = "stc_ts_lang_server"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lspower = "1.1.0"
stc_ts_ast_rnode = {path = "../ast_rnode"}
stc_ts_env = {path = "../analyzer/env"}
stc_ts_type_checker = {path = "../type_checker"}
stc_ts_types = {path = "../types"}
tokio = {version = "1.7.1", features = ["rt", "rt-multi-thread", "macros", "io-util", "io-std", "time", "fs"]}
