[package]
authors = ["강동윤 <kdy1@dudy.kr>"]
edition = "2018"
name = "stc-ts-lang-server"
publish = false
version = "0.1.0"

[dependencies]
anyhow = "1.0.37"
lsp-server = "0.5.0"
lsp-types = "0.86.0"
rayon = "1.5.0"
stc_ts_builtin_types = {path = "../builtin_types"}
stc_ts_env = {path = "../env"}
stc_ts_errors = {path = "../errors"}
stc_ts_type_checker = {path = "../type_checker"}
stc_ts_types = {path = "../types"}
structopt = "0.3.21"
swc_atoms = "0.2.5"
swc_common = "0.10.8"
