[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"
name = "stc_visit"
publish = false
version = "0.1.0"

[dependencies]
num-bigint = "0.2"
stc_visit_macros = {path = "./macros"}
swc_atoms = "0.2.6"
swc_common = "0.11.4"
swc_ecma_ast = "0.49.1"
