[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"
name = "stc_ts_checker_api"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.7.4"
async-trait = "0.1.51"
auto_impl = "0.4.1"
futures = "0.3.16"
stc_ts_errors = {path = "../errors/"}
stc_ts_types = {path = "../types/"}
stc_ts_utils = {path = "../utils/"}
stc_utils = {path = "../../utils/"}
swc_atoms = "0.2.6"
swc_common = "0.11.6"
tokio = {version = "1.10.0", features = ["full"]}
tracing = "0.1.26"
