[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"
name = "stc_ts_env"
publish = false
version = "0.1.0"

[dependencies]
derivative = "2.1.1"
parking_lot = "0.11.2"
rustc-hash = "1.1.0"
serde = "1.0.130"
stc_ts_storage = {path = "../../storage/"}
stc_ts_types = {path = "../../types/"}
string_enum = "0.3.1"
swc_atoms = "0.2.6"
swc_common = {version = "0.11.4", features = ["concurrent"]}
swc_ecma_ast = "0.49.1"
swc_ecma_parser = "0.66.0"
tracing = "0.1.26"
