[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"
name = "stc_ts_env"
publish = false
version = "0.1.0"

[dependencies]
derivative = "2.1.1"
stc_ts_storage = {path = "../../storage/"}
