[package]
authors = ["강동윤 <kdy1@dudy.kr"]
edition = "2018"
name = "stc_types"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "3"
fxhash = "0.2.1"
is-macro = "0.1.7"
num-bigint = {version = "0.2", features = ["serde"]}
num-traits = "0.2.12"
parking_lot = "0.11"
swc_atoms = "0.2.5"
swc_common = "0.10.6"
swc_ecma_ast = "0.35.0"
swc_ecma_utils = "0.25.0"
swc_ecma_visit = "0.21.0"
swc_visit = "0.2.2"
