[package]
authors = ["강동윤 <kdy1@dudy.kr>"]
edition = "2018"
name = "stc_ts_types"
publish = false
version = "0.0.0"

[dependencies]
dashmap = "3"
fxhash = "0.2.1"
is-macro = "0.1.7"
num-bigint = {version = "0.2", features = ["serde"]}
num-traits = "0.2.12"
parking_lot = "0.11"
rnode = {path = "../../rnode"}
smallvec = "1.6.0"
stc_ts_ast_rnode = {path = "../ast_rnode"}
stc_visit = {path = "../../visit"}
swc_atoms = "0.2.5"
swc_common = "0.10.9"
swc_ecma_ast = "0.37.3"
swc_ecma_utils = "0.27.3"
swc_ecma_visit = "0.23.3"
swc_visit = "0.2.2"
