[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"
name = "stc_ts_types"
publish = false
version = "0.0.0"

[features]
profile = []

[lib]

[dependencies]
dashmap = "3"
fxhash = "0.2.1"
is-macro = "0.1.7"
num-bigint = {version = "0.2", features = ["serde"]}
num-traits = "0.2.12"
once_cell = "1.8.0"
parking_lot = "0.11"
rnode = {path = "../../rnode"}
scoped-tls = "1.0.0"
smallvec = "1.6.0"
static_assertions = "1.1.0"
stc_ts_ast_rnode = {path = "../ast_rnode"}
stc_utils = {path = "../../utils/"}
stc_visit = {path = "../../visit"}
swc_atoms = "0.2.6"
swc_common = {version = "0.11.4", features = ["concurrent"]}
swc_ecma_ast = "0.49.1"
swc_ecma_utils = "0.41.0"
swc_ecma_visit = "0.35.1"
swc_visit = "0.2.5"
tracing = "0.1.26"
