[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"
name = "stc_ts_builtin_types"
publish = false
version = "0.0.0"

[dependencies]
fxhash = "0.2.1"
indexmap = "1.3.2"
once_cell = "1"
rayon = "1"
stc_ts_builtin_macro = {path = "./macros"}
swc_atoms = "0.2.9"
swc_common = "0.14.6"
swc_ecma_ast = "0.58.0"
swc_ecma_parser = "0.78.0"
swc_ecma_visit = "0.35.1"
