[package]
name = "stc_ts_dts_mutations"
version = "0.1.0"
authors = ["강동윤 <kdy1@dudy.kr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"
rnode = { path = "../../rnode" }
stc_ts_ast_rnode = { path = "../ast_rnode" }
stc_ts_types = { path = "../types" }
