[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2021"
name = "rnode_macros"
publish = false
version = "0.0.0"

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11.4"
pmutil = "0.5.3"
proc-macro2 = "1.0.24"
quote = "1.0.7"
syn = "1.0.54"
