[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"
name = "stc_ts_ast_rnode"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.2"
rnode = {path = "../../rnode"}
stc_utils = {path = "../../utils"}
stc_visit = {path = "../../visit"}
swc_atoms = "0.2.6"
swc_common = "0.10.21"
swc_ecma_ast = "0.46.0"
