[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2021"
name = "stc_visit"
publish = false
version = "0.1.0"

[dependencies]
num-bigint = "0.4.3"
rustc-hash = "1.1.0"
scoped-tls = "1.0.0"
stc_visit_macros = {path = "../stc_visit_macros"}
swc_atoms = "0.4.39"
swc_common = "0.29.37"
swc_ecma_ast = "0.100.2"
