[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2021"
name = "stc_ts_type_ops"
publish = false
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.7.0"
rnode = {path = "../rnode"}
rustc-hash = "1.1.0"
stc_ts_ast_rnode = {path = "../stc_ts_ast_rnode"}
stc_ts_base_type_ops = {path = "../stc_ts_base_type_ops"}
stc_ts_generics = {path = "../stc_ts_generics"}
stc_ts_types = {path = "../stc_ts_types"}
stc_ts_utils = {path = "../stc_ts_utils"}
stc_utils = {path = "../stc_utils"}
swc_atoms = "0.2.9"
swc_common = "0.14.6"
swc_ecma_ast = "0.58.0"
tracing = "0.1.26"
