[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"
name = "stc_ts_passes"
publish = false
version = "0.1.0"

[dependencies]
ahash = "0.7.2"
fxhash = "0.2.1"
rnode = {path = "../../rnode"}
stc_ts_ast_rnode = {path = "../ast_rnode"}
stc_ts_errors = {path = "../errors"}
stc_ts_types = {path = "../types"}
stc_ts_utils = {path = "../utils"}
stc_utils = {path = "../../utils"}
swc_atoms = "0.2.7"
swc_common = "0.11.6"
