[build]
incremental = false
rustflags = [
  "--cfg",
  "procmacro2_semver_exempt",
  "-Z",
  "thinlto=no",
  "-C",
  "target-feature=+sse2,+aes",
]

[net]
git-fetch-with-cli = true

[cargo-new]
email = "kdy1@dudy.kr"
name = "강동윤"

[profile.dev]
debug = 1
