[build]
rustflags = [
  "--cfg",
  "procmacro2_semver_exempt",
  "-Z",
  "thinlto=no",
  "-C",
  "target-feature=+sse2,+aes",
  "-Cprefer-dynamic",
  "-Zshare-generics=y",
]

[target.x86_64-apple-darwin]
rustflags = [
  "--cfg",
  "procmacro2_semver_exempt",
  "-Z",
  "thinlto=no",
  "-C",
  "target-feature=+sse2,+aes",
  "-Cprefer-dynamic",
  "-Zshare-generics=y",
  "-C",
  "link-arg=-fuse-ld=/usr/local/bin/zld",
]

[net]
git-fetch-with-cli = true

[cargo-new]
email = "kdy1997.dev@gmail.com"
name = "강동윤"
