[package]
name = "stc_ts_normalization"
version = "0.1.0"
authors = ["강동윤 <kdy1@dudy.kr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
