[package]
authors = ["강동윤 <kdy1@dudy.kr>"]
edition = "2018"
name = "stc_devtools"
publish = false
version = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
hex = "0.4.2"
sha-1 = "0.9"
slog = "2"
stc_checker = {path = "../../typescript/checker"}
swc_atoms = "0.2.5"
swc_common = { version = "0.10.6", features = ["concurrent"] }
swc_ecma_ast = "0.35.0"
swc_ecma_codegen = "0.41.4"
swc_ecma_parser = "0.43.1"
swc_ecma_utils = "0.25.0"
swc_ecma_visit = "0.21.0"
tempfile = "3"
