[package]
authors = ["강동윤 <kdy1@dudy.kr>"]
description = "Splitted to reduce compile time"
edition = "2018"
name = "stc_ts_ordering"
publish = false
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"
indexmap = "1.6.2"
petgraph = "0.5.1"
rnode = {path = "../../../rnode"}
stc_ts_ast_rnode = {path = "../../ast_rnode"}
stc_ts_types = {path = "../../types"}
stc_ts_utils = {path = "../../utils"}
