[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"
name = "stc_visit_macros"
publish = false
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
pmutil = "0.5.3"
proc-macro2 = "1.0.24"
quote = "1.0.7"
syn = {version = "1.0.54", features = ["full"]}
