[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"
name = "stc_ts_checker_impl"
publisg = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.51"
slog = "2.7.0"
stc_ts_checker_api = {path = "../checker_api/"}
stc_ts_dep_graph = {path = "../dep_graph/"}
stc_ts_dts = {path = "../dts"}
stc_ts_dts_mutations = {path = "../dts_mutations/"}
stc_ts_errors = {path = "../errors/"}
stc_ts_file_analyzer = {path = "../file_analyzer/"}
stc_ts_storage = {path = "../storage/"}
stc_ts_types = {path = "../types/"}
stc_ts_utils = {path = "../utils/"}
stc_utils = {path = "../../utils/"}
stc_visit = {path = "../../visit/"}
swc_atoms = "0.2.7"
swc_common = "0.11.6"
tokio = {version = "1.10.0", features = ["rt"]}
