[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"
name = "stc_ts_checker_impl"
publisg = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stc_ts_checker_api = {path = "../checker_api/"}
stc_ts_utils = {path = "../utils/"}
stc_utils = {path = "../../utils/"}
swc_atoms = "0.2.6"
swc_common = "0.11.6"
