[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"
name = "stc_ts_file_analyzer"
publish = false
version = "0.1.0"

[features]
default = ["fastpath"]
fastpath = []
profile = ["stc_ts_types/profile"]

[lib]

[dependencies]
backtrace = "0.3.60"
bitflags = "1.2.1"
dashmap = {version = "3", features = ["raw-api"]}
derivative = "2.1.1"
fxhash = "0.2.1"
indexmap = "1.6.1"
itertools = "0.10.0"
lexical = {version = "5.2.2", features = ["radix"]}
once_cell = "1.5.2"
petgraph = "0.5.1"
rayon = "1.5.0"
retain_mut = "0.1.1"
rnode = {path = "../../rnode"}
serde = "1.0.125"
smallvec = "1.5.1"
stc_arc_cow = {path = "../../utils/arc_cow"}
stc_ts_ast_rnode = {path = "../ast_rnode"}
stc_ts_base_type_ops = {path = "../base_type_ops/"}
stc_ts_builtin_types = {path = "../builtin_types"}
stc_ts_dts_mutations = {path = "../dts_mutations"}
stc_ts_env = {path = "../env"}
stc_ts_errors = {path = "../errors"}
stc_ts_file_analyzer_macros = {path = "./macros"}
stc_ts_generics = {path = "../generics"}
stc_ts_ordering = {path = "./ordering"}
stc_ts_storage = {path = "../storage"}
stc_ts_type_cache = {path = "../type_cache/"}
stc_ts_type_form = {path = "../type_form"}
stc_ts_type_ops = {path = "../type_ops"}
stc_ts_types = {path = "../types"}
stc_ts_utils = {path = "../utils"}
stc_utils = {path = "../../utils"}
string_enum = "0.3.1"
swc_atoms = "0.2.6"
swc_common = {version = "0.11.4", features = ["concurrent"]}
swc_ecma_ast = "0.49.1"
swc_ecma_codegen = "0.66.1"
swc_ecma_parser = "0.66.0"
swc_ecma_utils = "0.41.0"
tracing = "0.1.26"

[dev-dependencies]
stc_testing = {path = "../../testing"}
stc_ts_testing = {path = "../testing"}
swc_ecma_parser = "0.66.0"
swc_ecma_transforms = "0.63.0"
swc_ecma_visit = "0.35.1"
testing = "0.12.0"
