[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"
name = "stc_ts_module_loader"
publish = false
version = "0.1.0"

[lib]

[dependencies]
ahash = "0.7.6"
anyhow = "1"
auto_impl = "0.5.0"
dashmap = "3"
fxhash = "0.2"
log = "0.4.14"
num_cpus = "1"
once_cell = "1"
parking_lot = "0.11"
path-clean = "0.1.0"
petgraph = "0.5"
rayon = "1"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
stc_ts_types = {path = "../types"}
swc_atoms = "0.2.9"
swc_common = {version = "0.14.6", features = ["concurrent"]}
swc_ecma_ast = "0.58.0"
swc_ecma_parser = "0.78.0"
swc_ecma_visit = "0.44.0"
swc_fast_graph = "0.1.0"
swc_graph_analyzer = "0.1.0"
tracing = "0.1.26"
