[package]
authors = ["강동윤 <kdy1@dudy.kr>"]
build = "build.rs"
edition = "2018"
name = "stc_ts_type_checker"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = {version = "3", features = ["raw-api"]}
fxhash = "0.2.1"
once_cell = "1.5.2"
parking_lot = "0.11.1"
rnode = {path = "../../rnode"}
slog = {version = "2.7.0", features = ["release_max_level_off"]}
stc_ts_ast_rnode = {path = "../ast_rnode"}
stc_ts_builtin_types = {path = "../builtin_types"}
stc_ts_dts = {path = "../dts"}
stc_ts_errors = {path = "../errors/"}
stc_ts_file_analyzer = {path = "../file_analyzer"}
stc_ts_module_loader = {path = "../module_loader"}
stc_ts_storage = {path = "../storage"}
stc_ts_types = {path = "../types"}
stc_ts_utils = {path = "../utils"}
stc_utils = {path = "../../utils"}
swc_atoms = "0.2.5"
swc_common = { version = "0.10.12", features = ["concurrent", "tty-emitter"] }
swc_ecma_ast = "0.40.0"
swc_ecma_parser = "0.49.0"
swc_ecma_transforms = "0.38.1"
swc_ecma_visit = "0.26.0"

[dev-dependencies]
anyhow = "1.0.37"
ignore = "0.4.17"
serde = {version = "1.0.118", features = ["derive"]}
serde_json = "1.0.61"
stc_testing = {path = "../../testing"}
stc_ts_testing = {path = "../testing"}
swc_ecma_codegen = "0.47.0"
swc_ecma_utils = "0.30.0"
testing = "0.10.2"
testing_macros = "0.1.1"
walkdir = "2.3.1"
