[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"
name = "stc_arc_cow"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
servo_arc = "0.1.1"
stc_visit = {path = "../../visit/"}
swc_common = "0.11.8"
tracing = "0.1.26"
